### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [HelloRusk/vscode-markdown-tablemaker#7]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

**Comment by kaisugi** [comment]
OK, i’ll look into it

**Comment by kaisugi** [comment]
After reading the article, I decided **not** to provide the FLOSS version of this extension. I'm pretty satisfied with the Microsoft branded VS Code and thus I'm not willing to go against their terms of use.

Anyway, this snippet is quite simple and anyone can fork this project for those who use FLOSS VSCode :)

**Comment by noraj** [comment]
> After reading the article, I decided **not** to provide the FLOSS version of this extension. I'm pretty satisfied with the Microsoft branded VS Code and thus I'm not willing to go against their terms of use.
> 
> Anyway, this snippet is quite simple and anyone can fork this project for those who use FLOSS VSCode :)

You may have misunderstood the article, this is actually the opposite.
What's against MS ToS is to use VScode Marketplace on non-MS product so using VScode Marketplace on FLOSS version of code is forbidden. With FLOSS version of code you are only authorized to use Open VSX (open registry) that's why I'm asking you to push the extension there as well.

**Comment by kaisugi** [comment]
I see what you mean.
But I'm too busy to do anything about it right now, I'm sorry.
